# Generated by Django 2.2.5 on 2019-10-15 23:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=100)),
                ('idade_jogador', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('MASC', 'Masculino'), ('FEMI', 'Feminino')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida_personagem', models.FloatField()),
                ('vida_boss', models.FloatField()),
                ('dano_base_personagem', models.FloatField()),
                ('dano_final_personagem', models.FloatField()),
                ('dano_total_boss', models.FloatField()),
                ('porcent_def_personagem', models.DecimalField(decimal_places=2, max_digits=3)),
                ('porcent_def_boss', models.DecimalField(decimal_places=2, max_digits=3)),
                ('id_boss', models.IntegerField()),
                ('tempo_rodada', models.DateTimeField(auto_now_add=True)),
                ('rodada_batalha', models.PositiveIntegerField()),
                ('level_fase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id_jogo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_jogo', models.DateField(auto_now_add=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.Jogador')),
                ('jogo', models.ManyToManyField(related_name='rodadas', to='jogo.Rodada')),
            ],
        ),
    ]
