# Generated by Django 2.2.5 on 2019-10-25 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida_personagem', models.FloatField()),
                ('vida_boss', models.FloatField()),
                ('dano_atacante', models.FloatField()),
                ('probabilidade_ataque', models.DecimalField(decimal_places=2, max_digits=3)),
                ('probabilidade_defesa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('numero_dado', models.PositiveSmallIntegerField()),
                ('numero_rodada', models.PositiveIntegerField()),
                ('tempo_rodada', models.DateTimeField(auto_now_add=True)),
                ('numero_fase', models.IntegerField()),
                ('personagem_atacou', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jogo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_jogo', models.DateField(auto_now_add=True)),
                ('total_mortes', models.PositiveIntegerField(default=0)),
                ('escolha_final', models.BooleanField(null=True)),
                ('pk_rodada', models.ManyToManyField(blank=True, to='jogo.Rodada')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=32, unique=True)),
                ('data_nascimento', models.DateField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('genero', models.CharField(choices=[('MASC', 'Masculino'), ('FEMI', 'Feminino')], max_length=4)),
                ('pk_jogos', models.ManyToManyField(blank=True, to='jogo.Jogo')),
            ],
            options={
                'verbose_name_plural': 'Jogadores',
            },
        ),
    ]
