# Generated by Django 2.2.5 on 2019-10-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='pk_jogador',
        ),
        migrations.AddField(
            model_name='jogador',
            name='pk_jogos',
            field=models.ManyToManyField(to='jogo.Jogo'),
        ),
    ]
