# Generated by Django 2.2.5 on 2019-09-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gampeplay',
            name='rodada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
