# Generated by Django 2.2.5 on 2019-11-15 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='nome_completo',
        ),
    ]
