# Generated by Django 2.2.5 on 2019-09-19 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_gampeplay_rodada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batalha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida_jogador', models.IntegerField()),
                ('dano_jogador', models.IntegerField()),
                ('vida_boss', models.IntegerField()),
                ('dano_boss', models.IntegerField()),
                ('rodada', models.IntegerField()),
                ('level', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='id_jogo',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jogo',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.Batalha'),
        ),
        migrations.DeleteModel(
            name='Gampeplay',
        ),
    ]
