# Generated by Django 2.2.5 on 2019-10-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_auto_20191016_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodada',
            name='dano_final_personagem',
        ),
        migrations.AlterField(
            model_name='jogo',
            name='escolha_final',
            field=models.BooleanField(null=True),
        ),
    ]
