# Generated by Django 2.2.5 on 2019-10-17 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0003_auto_20191017_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='id_jogo',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
