# Generated by Django 2.2.5 on 2019-09-19 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0003_auto_20190919_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jogo', models.CharField(max_length=10)),
                ('dano_jogador', models.IntegerField()),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jogo.Jogo')),
            ],
        ),
    ]
