# Generated by Django 2.2.5 on 2019-10-17 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0004_auto_20191017_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='pk_jogos',
            field=models.ManyToManyField(null=True, to='jogo.Jogo'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='id_jogo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
