# Generated by Django 2.2.5 on 2019-09-20 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0004_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batalha', to='jogo.Batalha'),
        ),
    ]
