# Generated by Django 2.2.5 on 2019-10-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0006_auto_20191017_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='pk_rodada',
            field=models.ManyToManyField(blank=True, to='jogo.Rodada'),
        ),
    ]
