# Generated by Django 2.2.5 on 2019-09-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0006_auto_20190920_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_rodada', models.DateTimeField(auto_created=True)),
                ('vida_personagem', models.FloatField()),
                ('vida_boss', models.FloatField()),
                ('dano_base_personagem', models.FloatField()),
                ('dano_final_personagem', models.FloatField()),
                ('dano_total_boss', models.FloatField()),
                ('porcent_def_personagem', models.DecimalField(decimal_places=2, max_digits=3)),
                ('porcent_def_boss', models.DecimalField(decimal_places=2, max_digits=3)),
                ('id_boss', models.IntegerField()),
                ('rodada_batalha', models.IntegerField()),
                ('level_fase', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teste',
            name='jogo',
        ),
        migrations.AlterField(
            model_name='jogo',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.Rodada'),
        ),
        migrations.DeleteModel(
            name='Batalha',
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
