# Generated by Django 2.2.5 on 2019-10-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0007_auto_20191017_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='total_mortes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
