# Generated by Django 2.2.5 on 2019-10-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0008_jogo_total_mortes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='apelido',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
