# Generated by Django 2.2.5 on 2019-10-15 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0009_auto_20190928_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='id',
        ),
        migrations.AlterField(
            model_name='jogo',
            name='id_jogo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='rodada_batalha',
            field=models.PositiveIntegerField(),
        ),
    ]
