# Generated by Django 2.2.5 on 2019-10-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0009_auto_20191020_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
