# Generated by Django 2.2.5 on 2019-10-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0010_jogador_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='data_cadastro',
        ),
    ]
